#
# TosKose for Debian-based images
#

ARG TOSKERISER_IMAGE

FROM ${TOSKERISER_IMAGE} as toskosed

# https://github.com/docker/docker/issues/4032#issuecomment-34597177
ARG DEBIAN_FRONTEND=noninteractive

# TODO considering dl and manually install supervisord and its dependencies

RUN set -eux \
    && apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
    supervisor \
    && apt-get -qq clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && mkdir -p /toskose/{config,scripts} /var/log/supervisor \
    && touch /var/log/supervisor.log

COPY . /toskose/

ENTRYPOINT ["/toskose/scripts/entrypoint.sh"]