#
# TosKose for Debian-based images
#

ARG TOSKERISER_IMAGE
ARG SUPERVISOR_VERSION

FROM TOSKERISER_IMAGE as toskosed

# https://github.com/docker/docker/issues/4032#issuecomment-34597177
ARG DEBIAN_FRONTEND=noninteractive

RUN set -eux \
    && apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
    supervisor \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    mkdir -p /toskose/{config,logs}

# copy the supervisord's configuration
COPY base/configs/supervisor/supervisord.conf /toskose/config/supervisord.conf

ENTRYPOINT ["/usr/bin/supervisord","-c","/etc/supervisor/conf.d/supervisord.conf","-l","/logs/supervisor.logs"]
