# the image to be "toskosed"
ARG TOSCA_SRC_IMAGE
ARG TOSKOSE_BASE_IMG

FROM ${TOSKOSE_BASE_IMG} as base

# "toskose" a given image
FROM ${TOSCA_SRC_IMAGE} as toskosed

# copy the toskose-unit's supervisord bundle (supervisord + python 2.7.15)
WORKDIR /
# check: copy from remote image (no need to declare toskose_unit as an empty from)
# COPY --from=diunipisocc/toskose-unit:latest /toskose/ /toskose/
COPY --from=base /toskose/ /toskose/

# copy lifecyle scripts and artifacts of apps hosted by this image
COPY . /tmp/toskose/apps

# copy supervisord's config
WORKDIR /toskose/supervisord/config
RUN mv /tmp/toskose/apps/supervisord.conf ./supervisord.conf

WORKDIR /toskose/apps
RUN set -eu \
    && rm -rf test/ \
    && mv /tmp/toskose/apps/* /toskose/apps/ \
    && chmod -R 777 /toskose/apps/

### TEST ###
# FROM toskosed as toskosed-test
# WORKDIR /toskose

# RUN set -eu \
#     && apt-get update \
#     && apt-get install -qq \
#     tree \
#     && tree -a

# ### ### ###

FROM toskosed as release

WORKDIR /toskose

VOLUME /toskose/apps /toskose/supervisord/logs

ENTRYPOINT ["/bin/sh", "-c", "/toskose/supervisord/entrypoint.sh"]