# the image to be "toskosed"
ARG TOSCA_SRC_IMAGE
ARG TOSKOSE_BASE_IMAGE=diunipisocc/toskose-unit:latest

FROM ${TOSKOSE_BASE_IMAGE} as remote

# "toskose" a given image
FROM ${TOSCA_SRC_IMAGE} as toskosed

# copy from our remote image (Supervisor bundle)
# env/arg substitution not work in --from atm: https://github.com/moby/moby/issues/34482
# COPY --from=diunipisocc/toskose-unit:$TOSKOSE_UNIT_VERSION /toskose/ /toskose/

COPY --from=remote /toskose/ /toskose/

# copy from local context (e.g. scripts, artifacts)
COPY . /tmp/toskose/apps

# Supervisor config
WORKDIR /toskose/supervisord/config
RUN mv /tmp/toskose/apps/supervisord.conf ./supervisord.conf

WORKDIR /toskose/apps
RUN set -eu \
    && mv /tmp/toskose/apps/* /toskose/apps/ \
    && chmod -R 777 /toskose/apps/ \
    && rm -rf test/ /tmp/toskose/

WORKDIR /toskose
VOLUME /toskose/apps /toskose/supervisord/logs

ENTRYPOINT ["/toskose/supervisord/bundle/supervisord"]
CMD ["-c", "/toskose/supervisord/config/supervisord.conf"]