ARG APP_VERSION

ARG ALPINE_VERSION=3.8
ARG SUPERVISOR_VERSION=3.3.4

FROM alpine:$ALPINE_VERSION as toskose-init

ARG SUPERVISOR_VERSION
ENV SUPERVISOR_VERSION=$SUPERVISOR_VERSION
ENV TMP_PATH=/tmp

# add CA certificates for HTTPS + Bash
RUN apk update > /dev/null && \
    apk add --no-cache ca-certificates bash tree > /dev/null && \
    update-ca-certificates > /dev/null && \
    mkdir -p $TMP_PATH

WORKDIR $TMP_PATH
COPY base/ .

### START TESTING ###
FROM toskose-init as toskose-init-test

WORKDIR $TMP_PATH
RUN tree -a
### END TESTING ###

FROM toskose-init-test as release
LABEL maintainer.name="Matteo Bogo" \
      maintainer.email="matteo.bogo@gmail.com" \
      version=$APP_VERSION